[package]
name = "photo-cache"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
photo-catalog = { path = "../catalog" }
photo-domain = { path = "../domain" }
photo-metadata = { path = "../metadata" }
blake3.workspace = true
fs2.workspace = true
libc = "0.2.189"
image.workspace = true
thiserror.workspace = true
uuid.workspace = true
walkdir.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
image.workspace = true
