[package]
name = "photo-metadata"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["heic"]
heic = ["photo-codec/heic", "photo-domain/heic"]

[dependencies]
photo-domain = { path = "../domain", default-features = false }
photo-codec = { path = "../codec", default-features = false }
chrono.workspace = true
image.workspace = true
kamadak-exif.workspace = true
quick-xml.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
